# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0196b1bc57251d55a10732ea0f4d1afb5a9bb5f2d9974282b3b700a775e853bf2a3099fc6668042061e171f1bc91948fabd38dbf9ac831564bdf55d0dbf69d2a

test:
  secret_key_base: c5159ca4a0a8304d7a1ccfbb3adf368d35b1238a5896952b74d8390723eb6c09fa6784f76ab79f6b3bb8ffb3cb0c77d5463feb147bcd65d4457d6113b1284a6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
